CODE_PROFILER_LOGS_DIR = "/home/LogFiles/CodeProfiler"
CODE_PROFILER_INSTALLER_LOG_FILE = f"{CODE_PROFILER_LOGS_DIR}/installation.log"
CODE_PROFILER_TRACE_NAME = f"{CODE_PROFILER_LOGS_DIR}/profiler_trace.json"
PID_FILE_LOCATION = f"{CODE_PROFILER_LOGS_DIR}/master_process.pid"

GUNICORN_LOGFILE_SIGNAL_HANDLER_INFO = "Worker.handle_usr1 of <gunicorn.workers.sync.SyncWorker object"

APP_SETTING_TO_ENABLE_CODE_PROFILER = "APPSETTING_WEBSITE_ENABLE_DEFAULT_CODE_PROFILER"
CODE_PROFILER_SIGNAL_HANDLER_NOT_INITIALIZED_ENV_NAME = "CODE_PROFILER_SIGNAL_HANDLER_NOT_INITIALIZED"